### ISSUE TITLE
how to compiled the code of  cmod

### ISSUE THREAD

**Issue by Andrawzyf** [wujunning2011/Learning-NVDLA-Notes#1]
英伟达提供了用于软件开发的的C-model，可以向你请教一下，这个C-model源码下载了以后，怎么去编译么？直接下载了以后，在linux环境下编译？

**Comment by JunningWu** [comment]
是的，直接clone hw版本库，在里面有工具可以直接编译的。
$ git clone https://github.com/nvdla/hw.git
$ cd hw
$ make
$ tools/bin/tmake -build cmod_top
http://nvdla.org/vp.html
首先要确保所有工具的版本都要和他们的一致，否则会出现一些小的问题。

**Comment by Andrawzyf** [comment]
嗯，没想到你回复的这么快。。。真感谢，这段指令我看到了，貌似执行这一段指令之前是不是需要搭建Virtual Platform，而搭建搭建Virtual Platform是不是按照Documentation里面的来，因为搭建Virtual Platform好像就是安装一些必要的工具软件。

**Comment by Andrawzyf** [comment]
cd hw 后执行make 他不是自动执行完的，还要填写enter project name 然后后面括号有个默认的选项，是填那个么？

**Comment by JunningWu** [comment]
是的，我的情况是三个版本库都clone了，然后按照vp的文档走一遍就行

**Comment by Andrawzyf** [comment]
我是按照VP的文档走了一遍。。前面都还好，就是clone HW后执行tools/bin/tmake -build cmod_top，老说我--cant locate YAML.pm in @inc。。。。。你说的克隆三个版本库指的是？

**Comment by JunningWu** [comment]
YAML安装了吗？

**Comment by JunningWu** [comment]
三个版本库vp，sw，hw，因为我这边是做asic出身的，所以一开始是那hw做仿真用。后来出了vp和sw，就在vp上面做工作了。

**Comment by Andrawzyf** [comment]
嗨，我YAML安装好后，编译生成了 out_dir。编译成功生成了VMOD和cmod，那生成的Vmod是不是就可以搭建虚拟器来跑方针了？那如何生成pattern呢？

**Comment by JunningWu** [comment]
是的，生成了以后就能用VP仿真了。
什么pattern？

**Comment by Andrawzyf** [comment]
当我用VP仿真时候，想通过 执行make指令来make虚拟模拟器（在VP目录下执行）,但是执行 cmake -DCMAKE_INSTALL_PREFIX = build -DSYSTEMC_PREFIX = /usr/local/systemc-2.3.0/ -DNVDLA_HW_PREFIX = / usr / local / nvdla / hw -DNVDLA_HW_PROJECT = nv_full 这个的时候（目录填的我自己的），说在VP/models/memory 和CPU里面没有CMakeLists.txt文件，所以会CMAKE失败，但是我看官方的库里面确实也没有。。。这个问题您有碰到么？

**Comment by Andrawzyf** [comment]
问题解决~

**Comment by Andrawzyf** [comment]
请问你有用VP仿真过么？

**Comment by CrazyBingo** [comment]
我擦   NVDLA的人不回复   在这里开小灶啊。。。。

@JunningWu 请教个问题，就是tmake -build verif_sim的时候遇到CMD015 error 有没有遇到过：
[https://github.com/nvdla/hw/issues/102](url)

**Comment by Andrawzyf** [comment]
@CrazyBingo 你跑的怎么样了。VP搭起来了么

**Comment by CrazyBingo** [comment]
你怎么在温哥华、洛杉玑、西雅图 哈哈

还没有呢。。蛋疼的不知道VCS版本问题还是怎么的 现在-build verif_sim的时候出现CMD-015 error

guihub 沟通太缓慢： 加我微信：hanbinhdu吧。。。

**Comment by JunningWu** [comment]
我没有run过这个回归测试，都是跑单个测试例的。我的微信是Junning_Wu

**Comment by ghost** [comment]
[ 2212.159561] Exit:dla_handle_events, ret:0

The process can't continue.process fault when running nvdla_runtime on ZCU102.
