### ISSUE TITLE
Integration of DIGITS with NVDLA

### ISSUE THREAD

**Issue by ferin08** [wujunning2011/Learning-NVDLA-Notes#10]
Hi,

Can anyone help me by shredding some light of how the output files generated by DIGITS can be used by NVDLA.

Thanks.

**Comment by JunningWu** [comment]
? I do not understand your question clearly.

**Comment by ferin08** [comment]
Its okay now, the problem has been solved. 
I used DIGITS and got the output model files in the form of prototxt and I used that in the complier and got the basic.nvdla loadable file for the runtime test application.
I have loaded the file and currently waiting for the results.

**Comment by JunningWu** [comment]
running Lenet-5 on nvdla VP takes a very short time， just a few mins.

**Comment by ferin08** [comment]
What is to be expected after: 
./nvdla_runtime --loadable basic.nvdla
command returns "Test pass"?
How do we run a test example on it?
Please let me know if there is documentation for this

**Comment by ferin08** [comment]
How do we use '-s' to "launch test in server mode"?

We used LeNet model.
Also, I tested a few images using --rawdump.
But the output in output.dimg isn't changing (It the same output as the first time).
I am removing the file before testing each time. Is there something that I am missing?

**Comment by JunningWu** [comment]
you shall include image file. .jpg format is ok for me. and the rawdump indicates 0-9. Junning Wu Email:wujunning11@gmail.com Signature is customized by Netease Mail Master On 06/22/2018 10:55, ferin08 wrote: What is to be expected after: ./nvdla_runtime --loadable basic.nvdla command returns "Test pass"? How do we run a test example on it? Please let me know if there is documentation for this — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ferin08** [comment]
Yeah, I tried a jpeg file.
It still somehow remembers the first output. It's displaying only that. How do I get rid of it?

**Comment by ferin08** [comment]
Also could you shed some light on How do we use '-s' to "launch test in server mode"?

**Comment by ferin08** [comment]
Do you know anyway I could fix this issue? 

 I tested a few images using --rawdump. (tried both jpeg and png)
But the output in output.dimg isn't changing (It the same output as the first time).

**Comment by JunningWu** [comment]
can you list your full command list and your model, test image.
in my case, i can run lenet-5 from Berkely very well.

**Comment by JunningWu** [comment]
or you can use the pre-built loadable file firstly.

**Comment by ferin08** [comment]
I used DIGITS to get our Lenet model outputs. In that they use the MNIST database to train as shown in this link below:
https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md

**Comment by JunningWu** [comment]
@ferin08 have you solved your problem?
Here is what I have done to get the expected result:

1. based  on nvdlav1, and vp(no docker)
2. compile loadable file using UCB lenet caffemodel
3. using this image : http://ddl.escience.cn/f/QGNg , 

```
# ./nvdla_runtime --loadable lenet-20180426.nvdla  --image nums_jpg/img_3.jpg   
--rawdump
creating new runtime context...
Emulator starting
surface format: 0
dlaimg height: 28 x 28 x 1: LS: 32 SS: 0 Size: 896
submitting tasks...
[  199.072512] Enter:dla_read_network_config

```

4. and the result is 
```
# cat output.dimg 
0 5.96046e-08 5.96046e-07 2.50936e-05 9.11951e-06 4.17233e-07 0 2.98023e-06 3.70741e-05 1 # 
# 

```

**Comment by ferin08** [comment]
We were trying jpeg and .png files instead of .jpg and .pgm files which is why we were not getting the right output. Now everything works fine! Thank You!

**Comment by ghost** [comment]
[ 2212.159561] Exit:dla_handle_events, ret:0
The process can't continue.
